Add Kirigami QML library
ubports/ubuntu-touch-meta pull request #26
Opened 2018-09-11 17:29 UTC by Flohack74

This will resolve https://github.com/ubports/ubuntu-touch/issues/479 finally

2018-09-11 17:42 UTC, UniversalSuperBox requested changes
The development packages should be added to sdk-libs-dev so that Clickable containers will pull them in.

I believe that the Kirigami package should be added to sdk-libs rather than touch since it's part of the app development kit, and could be installed on non-Touch images too.

2018-09-15 00:25 UTC, UniversalSuperBox approved these changes

2018-09-15 00:26 UTC, UniversalSuperBox commented
I'll wait for a review from @bhdouglass since he's the one who will need to rebuild the Clickable containers. :)

2018-09-15 00:39 UTC, bhdouglass commented
LGTM

2018-09-15 00:40 UTC, bhdouglass approved these changes

2018-09-15 01:10 UTC, merged