Remove all unsuported frameworks
ubports/ubuntu-touch-meta pull request #7
Opened 2018-05-06 18:09 UTC by mariogrip

Since we have done such a big jump in both qt and toolchain version,
older frameworks are simply not supported. There is no way around this
but now is better then later.

DO NOT MERGE YET!

We need to update our coreapps to use the new framework before merging this.

2018-05-06 18:27 UTC, Flohack74 requested changes
Blocking Review

2018-05-06 18:31 UTC, mariogrip commented
Here is a quick forum post on how to upgrade the apps, https://forums.ubports.com/topic/1215/updating-apps-to-16-04 since its not only framework it might cause confusion, but policy also.

2018-05-06 21:20 UTC, NeoTheThird commented
Wait, why do we need the new policy and shouldn't we stick to the x.x naming scheme there? Is that a good idea?

2018-05-15 13:49 UTC, mariogrip commented
the policy change comes from canonical, and has already been implemented in apparmor by canonical. we did not make that change

2018-06-09 14:48 UTC, NeoTheThird requested changes
NOT for OTA-4. Just keeping this open, since we might want to remove the old frameworks at a later date.

2018-11-07 14:32 UTC, bhdouglass commented
I don't think it makes sense any longer to remove all the frameworks, but I would suggest we remove anything older than 15.04.x

2019-02-09 16:07 UTC, UniversalSuperBox commented
Closing, only frameworks older than 15.04 should be removed.

2019-02-09 16:07 UTC, closed without merging